### ISSUE TITLE
pdns_sniff 报错 不能记录入库

### ISSUE THREAD

**Issue by lianfeng30** [coffeehb/tools#2]
pdns_sniff.py -i en0
WARNING: No route found for IPv6 destination :: (no default route?)
[+] Start Recording......
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent-1.1rc3-py2.7-macosx-10.6-intel.egg/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "pdns_sniff.py", line 131, in run
    sniff(iface=interface, filter="udp and port 53", prn=packetHandler)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/sendrecv.py", line 570, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 118, in __init__
    self.ins = open_pcap(iface, 1600, self.promisc, 100)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 80, in <lambda>
    open_pcap = lambda *args,**kargs: _PcapWrapper_libpcap(*args,**kargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 66, in __init__
    self.pcap.open_live(*args, **kargs)
  File "/Library/Python/2.7/site-packages/pcap.py", line 86, in open_live
    def open_live(*args): return _pcap.pcapObject_open_live(*args)
Exception: en0: You don't have permission to capture on that device ((cannot open BPF device) /dev/bpf0: Permission denied)
<Greenlet at 0x1068bca50: run('en0')> failed with Exception

Exception Exception: 'pcapObject must be initialized via open_live(), open_offline(), or open_dead() methods' in <bound method _PcapWrapper_libpcap.__del__ of <pcap.pcapObject; proxy of <Swig Object of type 'pcapObject *' at 0x106a14ee0> >> ignored

root权限测试：
sudo python pdns_sniff.py -i en0
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "pdns_sniff.py", line 14, in <module>
    import MySQLdb as mysql
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent-1.1rc3-py2.7-macosx-10.6-intel.egg/gevent/builtins.py", line 58, in __import__
    result = _import(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent-1.1rc3-py2.7-macosx-10.6-intel.egg/gevent/builtins.py", line 58, in __import__
    result = _import(*args, **kwargs)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_mysql.so, 2): Library not loaded: /usr/local/opt/mysql/lib/libmysqlclient.20.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_mysql.so
  Reason: image not found

怎么回事？

**Comment by coffeehb** [comment]
不知道你解决了么，看样子像是安装的模块问题，确认一下MySQLdb连接mysql 是否正常以及scapy模块是否能抓到网卡流量。
